apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs
  namespace: production
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.10
    path: "/var/nfs/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-nfs
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: petclinic
    tier: mysql
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: production
  labels:
    app: petclinic
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: "MYSQL_USER"
          value: "petclinic"
        - name: "MYSQL_PASSWORD"
          value: "petclinic"
        - name: "MYSQL_DATABASE"
          value: "petclinic"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d  
      volumes:
      - name: config-volume
        configMap:
          name: mysql
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-nfs
---          
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: production
  labels:
    app: mysql
data:
  petclinic.cnf: |
    # Apply this config only on the master.
    [mysqld]
    bind-address = 0.0.0.0
