apiVersion: v1
kind: Pod
apiVersion: v1
kind: Pod
metadata:
  name: timecheck
  namespace: default
  labels:
    app: timecheck
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: host-path-volume
  - name: timestamp
    image: rstarmer/timestamp
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /clone
      name: host-path-volume
  volumes:
    - name: host-path-volume
      hostPath:
        path: /home/daemon/
